// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mygpqokqrkrohfocqohy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15Z3Bxb2txcmtyb2hmb2Nxb2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQ3ODIsImV4cCI6MjA2NTUwMDc4Mn0.DE0QHDGhrfApB2xpeJTwOT5b9hyeJ4x-yRnzAO0c_dE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);